name: strict_lints
description: >
  A strict linter config that enable as much rules as possible,
  and the infrastructure to sync from official api site.
version: 1.0.0
environment: { sdk: ^3.3.4 }

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
